defaults:
  - _self_

clip:
  model: "ViT-B/32"
  prompts: [
    "a photo of a airplane",
    "a photo of a automobile",
    "a photo of a bird",
    "a photo of a cat",
    "a photo of a deer",
    "a photo of a dog",
    "a photo of a frog",
    "a photo of a horse",
    "a photo of a ship",
    "a photo of a truck"
  ]

data:
    capture_batch_idx: [100, 200, 300]
    exp_name: "default_exp"
    class_a: "cat"
    class_b: "dog"
